### ISSUE TITLE
Small problem with missing C types and DecodeOptions struct literal

### ISSUE THREAD

**Issue by ppickfor** [kraman/go-netfilter-queue#1]
`
diff --git a/netfilter.go b/netfilter.go
index 98ce34a..cbd8239 100644
--- a/netfilter.go
+++ b/netfilter.go
@@ -57,8 +57,8 @@ func (p *NFPacket) SetRequeueVerdict(newQueueId uint16) {
 }

 type NFQueue struct {
-       h       *[0]byte
-       qh      *[0]byte
-       h       *C.struct_nfq_handle
-       qh      *C.struct_nfq_q_handle
      fd      C.int
      packets chan NFPacket
  }
  @@ -144,7 +144,7 @@ func (nfq *NFQueue) run() {
  //export go_callback
  func go_callback(queueId C.int, data *C.uchar, len C.int, cb *chan NFPacket) Verdict {
        xdata := C.GoBytes(unsafe.Pointer(data), len)
-       packet := gopacket.NewPacket(xdata, layers.LayerTypeIPv4, gopacket.DecodeOptions{true, true})
-       packet := gopacket.NewPacket(xdata, layers.LayerTypeIPv4, gopacket.DecodeOptions{Lazy: true, NoCopy: true})
      p := NFPacket{verdictChannel: make(chan Verdict), Packet: packet}
      select {
      case (*cb) <- p:
  `

**Comment by kraman** [comment]
@ppickfor do you mind sending that as a PR?

**Comment by balboah** [comment]
@kraman I think I experienced the same problem, should I PR here or to openshift/geard?

**Comment by balboah** [comment]
Oh it's actually kind of the same as the other PR,
see https://github.com/balboah/geard/compare/openshift:master...master
